### PR TITLE
Release 0.4.2

### PR DESCRIPTION
**Pull request by edwardloveall**
I picked 0.4.2 because it's mostly just internal updates with no API changes.

### CODE REVIEW

**Review by paulcsmith — APPROVED** [review]
Looks good 🎉

**Comment by paulcsmith** [comment]
Edward could you tag the commit as v0.4.2 and push up the tag? Shards uses fit tags to find the available versions

**Comment by edwardloveall** [comment]
Done!

**Comment by paulcsmith** [comment]
Thank you!

**Pull request merged**
